### ISSUE TITLE
Component redesign

### ISSUE THREAD

**Issue by gvonkoss** [Financial-Times/o-footer-services#6]
This whole component needs a bit of a do over. 
It should cater to IP, O&R, Polyfill Service, Origami &c, meaning that there are multiple variations of it in various scenarios, which is different for staff facing v customer facing.

I think we can break the sections up like this, more or less, keeping in mind that they are all  optional depending on the situation they are used in:

- Info, for additional context/text
- Contact (slack, github, email)
- Product logo
- Legal links (T&cs, Privacy Policies)
- Copyright

**Comment by draysonandstock** [comment]
New design for this can be found here (https://drive.google.com/open?id=1xy_gwWcD4eT2QwfcTBVrD2-Rk1gSjdN6)

In order to ensure we're compliant going forward I've gone with a single version (rather than having an internal and external version). I've emailed legal to confirm wording so cannot go live until we've had sign off. 

The attached is of the full version we can then just hide the additional parts when these aren't needed and for the other versions currently in the demos. Also the small link style for T&Cs and Privacy is new but we can discuss this and see how the normal style looks. 

Any questions let me know. 

![o-footer-services 2x](https://user-images.githubusercontent.com/11214093/43457259-31977278-94be-11e8-9ae0-9f3e1476155c.png)

**Comment by draysonandstock** [comment]
Legal has confirmed the four links (as in attached) should point to the same URLs as they do for the Masterbrand footer. 

![o-footer-services minimal xs 320px 2x](https://user-images.githubusercontent.com/11214093/44776512-26c60a80-ab70-11e8-910f-5cc754e5eed2.png)
![o-footer-services minimal 2x](https://user-images.githubusercontent.com/11214093/44776513-26c60a80-ab70-11e8-8143-903433b55c41.png)

For all design variants please see Sketch file.

**Comment by gvonkoss** [comment]
Success! https://github.com/Financial-Times/o-footer-services/pull/7
